name: Validate Model

on:
  push:
    branches: [main]  # Trigger the workflow on push events to the main branch
  pull_request:
    branches: [main]  # Trigger the workflow on pull request events targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the repository to the runner

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up the Python environment
      with:
        python-version: '3.13'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt  # Install the dependencies listed in requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"  # Run unit tests located in the tests directory