name: Deploy to Render

on:
  push:
    branches: [main]  # Trigger the workflow on push events to the main branch
  pull_request:
    branches: [main]  # Trigger the workflow on pull request events targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository to the runner

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up the Python environment
        with:
          python-version: '3.13'  # Specify the Python version to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install the dependencies listed in requirements.txt

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8  # Use the Render deploy action to deploy the application
        with:
          service-id: srv-cukel0d6l47c73cao6cg  # Specify the Render service ID
          api-key: rnd_xWgCqz4tyLnC6P17BUX8ICtoNklI  # Specify the Render API key